name: Show secret

on:
  workflow_dispatch

jobs:
  secret:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Get Key
        run: echo "my bal is ${{ secrets.OPENAI_API_KEY }}"
          
